apps/crud/models.py
from datetime import datetime

from apps.app import db, login_manager
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash

# db.Modelを継承してモデルを作成
class User(db.Model, UserMixin):
    # テーブル名を定義
    __tablename__ = "users"

    # カラムを定義
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String, index=True)
    email = db.Column(db.String, unique=True, index=True)
    password_hash = db.Column(db.String)
    created_at = db.Column(db.DateTime, default=datetime.now)
    updated_at = db.Column(db.DateTime, default=datetime.now, onupdate=datetime.now)

    # パスワードをハッシュ化
    @property
    def password(self):
        raise AttributeError("読み取り不可")

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        # パスワードが正しいかチェック
        return check_password_hash(self.password_hash, password)

    def is_duplicate_email(self):
        # メールアドレスが重複していないかチェック
        return User.query.filter_by(email=self.email).first() is not None

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)

apps/crud/forms.py
from flask_wtf import FlaskForm
from wtforms import PasswordField, StringField, SubmitField
from wtforms.validators import DataRequired, Email, length

class UserForm(FlaskForm):
    # フォームの各項目ごとにラベルとバリデーターを設定する

    # ユーザー名
    username = StringField(
        "ユーザー名",
        validators=[
            DataRequired(message="ユーザー名は必須です。"),
            length(max=30, message="ユーザー名は30文字以内で入力してください。"),
        ],
    )

    # メールアドレス
    email = StringField(
        "メールアドレス",
        validators=[
            DataRequired(message="メールアドレスは必須です。"),
            Email(message="メールアドレスの形式で入力してください。"),
        ],
    )

    # パスワード
    password = PasswordField(
        "パスワード",
        validators=[
            DataRequired(message="パスワードは必須です。"),
        ],
    )

    # 送信ボタンの文言設定
    submit = SubmitField("新規登録")

apps/crud/__init__.py
import apps.crud.models

apps/crud/views.py
from apps.app import db
from apps.crud.models import User
from apps.crud.forms import UserForm
from flask import Blueprint, render_template,redirect, url_for
from flask_login import login_required

crud = Blueprint(
    "crud",
    __name__,
    template_folder="templates",
    static_folder="static",
)

@crud.route("/")
@login_required
def index():
    return render_template("crud/index.html")


# ユーザーの新規作成画面
@crud.route("/user/new", methods=["GET", "POST"])
@login_required
def create_user():
    form = UserForm()

    if form.validate_on_submit():
        user = User(
            username=form.username.data,
            email=form.email.data,
            password=form.password.data,
        )

        db.session.add(user)
        db.session.commit()

        return redirect(url_for("crud.users"))

    return render_template("crud/create.html", form=form)


# ユーザーの一覧画面
@crud.route("/users")
@login_required
def users():
    users = User.query.all()
    return render_template("crud/index.html", users=users)


# ユーザー編集画面
@crud.route("/user/<int:user_id>/edit", methods=["GET", "POST"])
@login_required
def edit_user(user_id):
    form = UserForm()
    user = User.query.get(user_id)
    if(form.validate_on_submit()):
        user.username = form.username.data
        user.email = form.email.data
        user.password = form.password.data
        db.session.add(user)
        db.session.commit()
        return redirect(url_for("crud.users"))

    return render_template("crud/edit.html", user=user, form=form)


@crud.route("/user<int:user_id>/delete", methods=["POST"])
@login_required
def delete_user(user_id):
    user = User.query.get(user_id)
    db.session.delete(user)
    db.session.commit()
    return redirect(url_for("crud.users"))

@crud.route("/sql")
@login_required
def sql():
    # db.session.query(User).all()
    # db.session.query(User).first()
    # user = User(
    #     username="myname2",
    #     email="my2@example.com",
    #     password="MyPassW0rd"
    # )
    # db.session.add(user)
    # db.session.commit()
    # db.session.query(User).paginate(1, 1, False)
    # db.session.query(User).filter_by(id=2, username="myname").all()
    # db.session.query(User).filter(User.id == 2, User.username == "myname").all()
    # user = db.session.query(User).filter_by(id=2).first()
    # user.username = "myname modified"
    # db.session.add(user)
    # db.session.commit()
    db.session.query(User).filter_by(id=2).delete()
    db.session.commit()
    return "コンソールログを確認してください"

apps/crud/templates/crud/base.html
<!doctype html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('crud.static', filename='style.css') }}">
</head>
<body>
{% block content %}{% endblock %}
</body>
</html>

apps/crud/templates/crud/create.html
{% extends "crud/base.html" %}
{% block title %}ユーザー新規作成{% endblock %}
{% block content %}
<h2>ユーザー新規作成</h2>
<form action="{{ url_for('crud.create_user') }}" method="POST" novalidate="novalidate">
    {{ form.csrf_token }}
    <p>
        {{ form.username.label }} {{ form.username(placeholder="ユーザー名")}}
    </p>
    {% for error in form.username.errors %}
    <span style="color:red;">{{ error }}</span>
    {% endfor %}

    <p>
        {{ form.email.label }} {{ form.email(placeholder="メールアドレス") }}
    </p>
    {% for error in form.email.errors %}
    <span style="color:red;">{{ error }}</span>
    {% endfor %}
    <p>
        {{ form.password.label }} {{ form.password(placeholder="パスワード") }}
    </p>
    {% for error in form.password.errors %}
    <span style="color:red;">{{ error }}</span>
    {% endfor %}

    <p>{{ form.submit() }}</p>
</form>
{% endblock %}

apps/crud/templates/crud/edit.html
{% extends "crud/base.html" %}
{% block title %}ユーザー編集{% endblock %}
{% block content %}
<h2>ユーザー編集</h2>
<form action="{{ url_for('crud.edit_user', user_id=user.id) }}" method="POST" novalidate="novalidate">
    {{ form.csrf_token }}
    <p>
        {{ form.username.label }} {{ form.username(value=user.username, placeholder="ユーザー名")}}
    </p>
    {% for error in form.username.errors %}
    <span style="color:red;">{{ error }}</span>
    {% endfor %}

    <p>
        {{ form.email.label }} {{ form.email(value=user.email, placeholder="メールアドレス") }}
    </p>
    {% for error in form.email.errors %}
    <span style="color:red;">{{ error }}</span>
    {% endfor %}
    <p>
        {{ form.password.label }} {{ form.password(value="", placeholder="パスワード") }}
    </p>
    {% for error in form.password.errors %}
    <span style="color:red;">{{ error }}</span>
    {% endfor %}

    <p><input type="submit" value="更新" /></p>
</form>
<form action="{{ url_for('crud.delete_user', user_id=user.id) }}" method="POST">
    {{ form.csrf_token }}
    <p><input type="submit" value="削除" /></p>
</form>
{% endblock %}

apps/crud/templates/crud/index.html
{% extends "crud/base.html" %}
{% block title %} ユーザー一覧 {% endblock %}
{% block content %}
<h2>ユーザーの一覧</h2>
<a href="{{ url_for('crud.create_user') }}">ユーザー新規作成</a>
<table>
    <tr>
        <th>ユーザーID</th>
        <th>ユーザー名</th>
        <th>メールアドレス</th>
        <th></th>
    </tr>
    {% for user in users %}
    <tr>
        <td>{{ user.id }}</td>
        <td>{{ user.username }}</td>
        <td>{{ user.email }}</td>
        <td><a href="{{ url_for('crud.edit_user',user_id=user.id) }}">編集</a></td>
    </tr>
    {% endfor %}
</table>
{% endblock %}